/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_rag_design;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author mettr
 */

public class Register_form extends javax.swing.JFrame {
    
    // to create a variable to set the image path
    String image_path = null;

    /**
     * Creates new form Register_form
     */
    public Register_form() {
        initComponents();
        //create center the form
        this.setLocationRelativeTo(null);
        // to create border in reg title
        Border reg_title = BorderFactory.createMatteBorder(0, 1, 1, 1, Color.yellow);
        jPanel_reg_title.setBorder(reg_title);
        // to create border close and minimize button
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_minimize.setBorder(label_border);
        jLabel_close.setBorder(label_border);
        
        ButtonGroup bg = new ButtonGroup();
        bg.add(jRadioButton_male);
        bg.add(jRadioButton_female);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_minimize = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jPanel_reg_title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_reg_username = new javax.swing.JTextField();
        jPasswordField_reg1 = new javax.swing.JPasswordField();
        jPasswordField_reg2 = new javax.swing.JPasswordField();
        jTextField_reg_fullName = new javax.swing.JTextField();
        jRadioButton_female = new javax.swing.JRadioButton();
        jButton_selectImage = new javax.swing.JButton();
        jRadioButton_male = new javax.swing.JRadioButton();
        jButton_register = new javax.swing.JButton();
        jTextField_phone_no = new javax.swing.JTextField();
        jLabel_image_path = new javax.swing.JLabel();
        jLabel_back_singIn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel_minimize.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_minimize.setText(" - ");
        jLabel_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseExited(evt);
            }
        });

        jLabel_close.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_close.setText("X");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseExited(evt);
            }
        });

        jPanel_reg_title.setBackground(new java.awt.Color(0, 84, 140));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Register form");

        javax.swing.GroupLayout jPanel_reg_titleLayout = new javax.swing.GroupLayout(jPanel_reg_title);
        jPanel_reg_title.setLayout(jPanel_reg_titleLayout);
        jPanel_reg_titleLayout.setHorizontalGroup(
            jPanel_reg_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_reg_titleLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel_reg_titleLayout.setVerticalGroup(
            jPanel_reg_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_reg_titleLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(jPanel_reg_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel_minimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_close)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_minimize)
                    .addComponent(jLabel_close))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel_reg_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Full Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Username");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Password");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Confirm Password");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Phone");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Gender");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Image");

        jTextField_reg_username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_reg_username.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_reg_username.setText("username");
        jTextField_reg_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_reg_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_reg_usernameFocusLost(evt);
            }
        });

        jPasswordField_reg1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField_reg1.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField_reg1.setText("password");
        jPasswordField_reg1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_reg1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_reg1FocusLost(evt);
            }
        });

        jPasswordField_reg2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField_reg2.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField_reg2.setText("password");
        jPasswordField_reg2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_reg2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_reg2FocusLost(evt);
            }
        });

        jTextField_reg_fullName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_reg_fullName.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_reg_fullName.setText("full_name");
        jTextField_reg_fullName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_reg_fullNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_reg_fullNameFocusLost(evt);
            }
        });
        jTextField_reg_fullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_reg_fullNameActionPerformed(evt);
            }
        });

        jRadioButton_female.setText("Female");

        jButton_selectImage.setText("Select image");
        jButton_selectImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_selectImageActionPerformed(evt);
            }
        });

        jRadioButton_male.setSelected(true);
        jRadioButton_male.setText("Male");

        jButton_register.setBackground(new java.awt.Color(255, 51, 51));
        jButton_register.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jButton_register.setForeground(new java.awt.Color(255, 255, 255));
        jButton_register.setText("Register");
        jButton_register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_registerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_registerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_registerMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton_registerMousePressed(evt);
            }
        });
        jButton_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registerActionPerformed(evt);
            }
        });

        jTextField_phone_no.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_phone_no.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_phone_no.setText("0123****");
        jTextField_phone_no.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_phone_noFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_phone_noFocusLost(evt);
            }
        });
        jTextField_phone_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_phone_noKeyTyped(evt);
            }
        });

        jLabel_image_path.setForeground(new java.awt.Color(153, 153, 153));
        jLabel_image_path.setText("image_path");

        jLabel_back_singIn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_back_singIn.setText("  <<  ");
        jLabel_back_singIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_back_singInMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_back_singInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_back_singInMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_reg_username)
                    .addComponent(jPasswordField_reg1)
                    .addComponent(jPasswordField_reg2, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                    .addComponent(jTextField_reg_fullName)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jRadioButton_male)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton_female))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton_selectImage)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_image_path))
                    .addComponent(jTextField_phone_no))
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(jButton_register, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_back_singIn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_reg_fullName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_reg_username, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jPasswordField_reg1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jPasswordField_reg2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(3, 3, 3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_phone_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton_male)
                            .addComponent(jRadioButton_female))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_selectImage)
                            .addComponent(jLabel_image_path))))
                .addGap(67, 67, 67)
                .addComponent(jButton_register, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel_back_singIn)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);

    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    private void jLabel_minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_minimize.setBorder(label_border);
        jLabel_minimize.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_minimizeMouseEntered

    private void jLabel_minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseExited
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_minimize.setBorder(label_border);
        jLabel_minimize.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_minimizeMouseExited

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jLabel_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_close.setBorder(label_border);
        jLabel_close.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_closeMouseEntered

    private void jLabel_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseExited
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_close.setBorder(label_border);
        jLabel_close.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_closeMouseExited

    private void jTextField_reg_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_reg_usernameFocusGained
        // TODO add your handling code here:
        //clear the username if focus
        if(jTextField_reg_username.getText().trim().toLowerCase().equals("username"))
        {
            jTextField_reg_username.setText("");
            jTextField_reg_username.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_reg_usernameFocusGained

    private void jTextField_reg_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_reg_usernameFocusLost
        // TODO add your handling code here:
        //if the text field is equal to username or empty
        //we will set the "username" text in the field
        if(jTextField_reg_username.getText().trim().equals("") || jTextField_reg_username.getText().trim().toLowerCase().equals("username")){
            jTextField_reg_username.setText("username");
            jTextField_reg_username.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextField_reg_usernameFocusLost

    private void jPasswordField_reg1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_reg1FocusGained
        // TODO add your handling code here:
        //clear the jPasswordField if focus

        // to get password text
        String pass = String.valueOf(jPasswordField_reg1.getPassword());

        if(pass.trim().toLowerCase().equals("password"))
        {
            jPasswordField_reg1.setText("");
            jPasswordField_reg1.setForeground(Color.black);
        }
    }//GEN-LAST:event_jPasswordField_reg1FocusGained

    private void jPasswordField_reg1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_reg1FocusLost
        // TODO add your handling code here:
        //if the password field is equal to password or empty
        //we will set the "password" text in the field

        // to get password text
        String pass = String.valueOf(jPasswordField_reg1.getPassword());

        if(pass.trim().equals("") || pass.trim().toLowerCase().equals("password")){
            jPasswordField_reg1.setText("password");
            jPasswordField_reg1.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jPasswordField_reg1FocusLost

    private void jPasswordField_reg2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_reg2FocusGained
        // TODO add your handling code here:
        String pass = String.valueOf(jPasswordField_reg2.getPassword());

        if(pass.trim().toLowerCase().equals("password"))
        {
            jPasswordField_reg2.setText("");
            jPasswordField_reg2.setForeground(Color.black);
        }
    }//GEN-LAST:event_jPasswordField_reg2FocusGained

    private void jPasswordField_reg2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_reg2FocusLost
        // TODO add your handling code here:
        String pass = String.valueOf(jPasswordField_reg2.getPassword());

        if(pass.trim().equals("") || pass.trim().toLowerCase().equals("password")){
            jPasswordField_reg2.setText("password");
            jPasswordField_reg2.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jPasswordField_reg2FocusLost

    private void jTextField_reg_fullNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_reg_fullNameFocusGained
        // TODO add your handling code here:
        //clear the username if focus
        if(jTextField_reg_fullName.getText().trim().toLowerCase().equals("full_name"))
        {
            jTextField_reg_fullName.setText("");
            jTextField_reg_fullName.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_reg_fullNameFocusGained

    private void jTextField_reg_fullNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_reg_fullNameFocusLost
        // TODO add your handling code here:
        //if the text field is equal to username or empty
        //we will set the "username" text in the field
        if(jTextField_reg_fullName.getText().trim().equals("") || jTextField_reg_fullName.getText().trim().toLowerCase().equals("full_name")){
            jTextField_reg_fullName.setText("full_name");
            jTextField_reg_fullName.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextField_reg_fullNameFocusLost

    private void jButton_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_registerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_registerMouseClicked

    private void jButton_registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_registerMouseEntered
        // TODO add your handling code here:
        //jbutton background
        jButton_register.setBackground(new Color(0,101,183));
    }//GEN-LAST:event_jButton_registerMouseEntered

    private void jButton_registerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_registerMouseExited
        // TODO add your handling code here:
        //jbutton background
        jButton_register.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_jButton_registerMouseExited

    private void jButton_registerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_registerMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_registerMousePressed

    private void jButton_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registerActionPerformed
        // TODO add your handling code here:
        String fname = jTextField_reg_fullName.getText();
        String uname = jTextField_reg_username.getText();
        String pass1 = String.valueOf(jPasswordField_reg1.getPassword());
        String pass2 = String.valueOf(jPasswordField_reg2.getPassword());
        String phone = jTextField_phone_no.getText();
        
//        String fname = jTextField_reg_fullName.getText();
//        String username = jTextField_reg_username.getText();
//        String pass1 = String.valueOf(jPasswordField_reg1.getPassword());
//        String pass2 = String.valueOf(jPasswordField_reg2.getPassword());
//        String phone = jTextField_phone_no.getText();
        String gender = "Male";
        
        if(jRadioButton_female.isSelected()){
            gender = "Female";
        }
        if(varifyfields()){
            if(!checkUsername(uname)){
                PreparedStatement ps;
                ResultSet rs;
                
                String registerUserQuery = "INSERT INTO `users`(`full_name`, `username`, `password`, `phone`, `gender`, `picture`) VALUES (?,?,?,?,?,?)";
                
                try {
                    ps = My_CNX.getConnection().prepareStatement(registerUserQuery);
                    ps.setString(1, fname);
                    ps.setString(2, uname);
                    ps.setString(3, pass1);
                    ps.setString(4, phone);
                    ps.setString(5, gender);
                    
                    try {
                        //save the image as blob in the database
                        if(image_path != null){
                            InputStream image = new FileInputStream(new File(image_path));
                            ps.setBlob(6, image);
                        }else{
                            ps.setNull(6, java.sql.Types.NULL);
                        }
                        
                        if(ps.executeUpdate() != 0){
                            JOptionPane.showMessageDialog(null, "Your account has been created");
                        }else{
                            JOptionPane.showMessageDialog(null, "Error: check your information");
                        }
                        
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(Register_form.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Register_form.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

//        PreparedStatement st;
//        ResultSet rs;
//
//        // to get username and password
//        String username = jTextField_username.getText();
//        String password = String.valueOf(jPasswordField.getPassword());

        //create a select query to check if the username and password exist
        //in the database
//
//        try {
//            st = My_CMX.getConnection().prepareStatement("SELECT * FROM `users` WHERE `username` = ? AND `password` = ?");
//            st.setString(1, username);
//            st.setString(2, password);
//            rs = st.executeQuery();
//
//            if(rs.next()){
//                // to show a new form
//                Menu_Form form = new Menu_Form();
//                form.setVisible(true);
//                form.pack();
//                form.setLocationRelativeTo(null);
//                // close the current form/activity "login form"
//                this.dispose();
//
//            }else{
//                // to error message
//                JOptionPane.showMessageDialog(null, "Invalid username / password","Login Error",2);
//            }
//
//        } catch (SQLException ex) {
//            Logger.getLogger(Login_form.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jButton_registerActionPerformed

    private void jTextField_reg_fullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_reg_fullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_reg_fullNameActionPerformed

    private void jTextField_phone_noFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_phone_noFocusGained
        // TODO add your handling code here:
        if(jTextField_phone_no.getText().trim().toLowerCase().equals("0123****"))
        {
            jTextField_phone_no.setText("");
            jTextField_phone_no.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_phone_noFocusGained

    private void jTextField_phone_noFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_phone_noFocusLost
        // TODO add your handling code here:
        if(jTextField_phone_no.getText().trim().equals("") || jTextField_phone_no.getText().trim().toLowerCase().equals("0123****")){
            jTextField_phone_no.setText("0123****");
            jTextField_phone_no.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextField_phone_noFocusLost

    private void jTextField_phone_noKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_phone_noKeyTyped
        // TODO add your handling code here:
        // to allow only number 
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_phone_noKeyTyped

    private void jButton_selectImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_selectImageActionPerformed
        // TODO add your handling code here:
        // to select an image and set from your computer
        String path = null;
        
        JFileChooser chooser = new JFileChooser();
        
        chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        
        //file extension 
        FileNameExtensionFilter extension = new FileNameExtensionFilter("*Images","jpg","png","jpeg");
        chooser.addChoosableFileFilter(extension);
        
        int filestate = chooser.showSaveDialog(null);
        
        // to check if the user select an image
        if(filestate == JFileChooser.APPROVE_OPTION){
            File selectedImage = chooser.getSelectedFile();
            path = selectedImage.getAbsolutePath();
            jLabel_image_path.setText(path);
            
            image_path = path;
        }
    }//GEN-LAST:event_jButton_selectImageActionPerformed

    private void jLabel_back_singInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_back_singInMouseEntered
        // TODO add your handling code here:
        Border sing_up_link = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.yellow);
        jLabel_back_singIn.setBorder(sing_up_link);
    }//GEN-LAST:event_jLabel_back_singInMouseEntered

    private void jLabel_back_singInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_back_singInMouseExited
        // TODO add your handling code here:
        jLabel_back_singIn.setBorder(null);
    }//GEN-LAST:event_jLabel_back_singInMouseExited

    private void jLabel_back_singInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_back_singInMouseClicked
        // TODO add your handling code here:
        Login_form lf = new Login_form();
        lf.setVisible(true);
        lf.pack();
        lf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel_back_singInMouseClicked

    // to create a function to verify the empty fields
    public boolean varifyfields(){
        String fname = jTextField_reg_fullName.getText();
        String uname = jTextField_reg_username.getText();
        String pass1 = String.valueOf(jPasswordField_reg1.getPassword());
        String pass2 = String.valueOf(jPasswordField_reg2.getPassword());
        String phone = jTextField_phone_no.getText();
        
        //to check empty fields
        if(fname.trim().equals("full_name") || uname.trim().equals("username") || pass1.trim().equals("password") || pass2.trim().equals("password") || phone.trim().equals("0123****")){
            
            JOptionPane.showMessageDialog(null, "One or more fields are empty","Empty fields", 2);
            return false;
        }
        // to check if the two password are equals
        else if(!pass1.equals(pass2)){
            JOptionPane.showMessageDialog(null, "Password is not match","Confirm password", 2);
            return false;
        }
        // is everyting is ok
        else{
            return true;
        }
        
    }
    
    // to create a function to check if the entred username already exists in the database
    public boolean checkUsername(String username){
        
        PreparedStatement st;
        ResultSet rs;
        boolean username_exist = false;
        
        String query = "SELECT * FROM `users` WHERE `USERNAME` = ?";
        
        try {
            st = My_CNX.getConnection().prepareStatement(query);
            st.setString(1, username);
            rs = st.executeQuery();
            
            if(rs.next()){
                username_exist = true;
                JOptionPane.showMessageDialog(null, "This username is aleady taken, choose another one", "username failed", 2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Register_form.class.getName()).log(Level.SEVERE, null, ex);
        }
        return username_exist;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_register;
    private javax.swing.JButton jButton_selectImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_back_singIn;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_image_path;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel_reg_title;
    private javax.swing.JPasswordField jPasswordField_reg1;
    private javax.swing.JPasswordField jPasswordField_reg2;
    private javax.swing.JRadioButton jRadioButton_female;
    private javax.swing.JRadioButton jRadioButton_male;
    private javax.swing.JTextField jTextField_phone_no;
    private javax.swing.JTextField jTextField_reg_fullName;
    private javax.swing.JTextField jTextField_reg_username;
    // End of variables declaration//GEN-END:variables
}
